[package]
name = "dynamite-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Command-line interface for the DYNAMITE gene caller."

[[bin]]
name = "dynamite"
path = "src/main.rs"

[dependencies]
dynamite-core = { path = "../dynamite-core" }
anyhow = { workspace = true }
clap = { workspace = true }
